### ISSUE TITLE
Support utf8 filenames

### ISSUE THREAD

**Issue by cedral** [boostorg/beast#1010] opened 2018-02-06 22:11 UTC
I had to add an assign function to value_type so I could open the file externally and thus use CreateFileW to support filenames that depend on unicode (windows doesn't natively support UTF-8) could you incorporate this into your code?

```
inline
void
basic_file_body<file_win32>::
value_type::
assign(file_win32::native_handle_type handle, error_code& ec)
{
  file_.native_handle(handle);
  file_.seek(0, ec);
  if (ec)
    return;
  size_ = file_.size(ec);
  if (ec)
  {
    close();
    return;
  }
  first_ = 0;
  last_ = size_;
}
```

**Comment by vinniefalco** [comment] 2018-02-07 00:04
Beast is supposed to convert utf8 for you on Windows, I have just not written it yet...

**Comment by cedral** [comment] 2018-02-09 22:42
That doesn't make for a very complete solution. Existing windows applications that are well written for internationalization will be storing filenames in wchar_t form. So that would mean 2 conversions anytime anybody wants to use your open function. They convert wide character to UTF-8 and then you convert it back. To avoid all that extra work I think it would be better to either allow assigning externally opened handles (which matches the ASIO interface) or provide a wide character open function on windows (which is how windows handles std::fstream). Alternatively you could do what boost streams does and take a boost::filesystem::path which can be created from either wide or narrow filename and only narrows as needed. I reserved this solution for last because it will require heap allocation which can get expensive in a multithreaded server.

**Comment by cedral** [comment] 2018-02-12 13:58
Thank you. That is the second time you have pointed me to a better way to do what I was trying to do.

**Comment by vinniefalco** [comment] 2018-02-12 15:22
Actually, Beast advertises utf-8 filename support but it is currently unimplemented so if it is okay I will keep this issue open since it reflects a defect - thanks for reminding me!

**Comment by vinniefalco** [comment] 2019-07-07 04:01
Duplicate of #793

**Closed by vinniefalco** 2019-07-07 04:01 UTC
Labels: Bug
