### ISSUE TITLE
Support -fno_exceptions -DBOOST_NO_EXCEPTIONS within Beast

### ISSUE THREAD

**Issue by azuretheseeker** [boostorg/beast#1177] opened 2018-07-03 20:27 UTC
Beast currently does not support compilation with:
-fno_exceptions
even when the following are defined:
-DBOOST_NO_EXCEPTIONS
-DBOOST_EXCEPTION_DISABLE

read.ipp has multiple try/catch clauses that do not respect this configuration.

As per all boost libraries, one of the goals is to allow the user to define their own error handling mechanism, and enabling exceptions still degrades performance in real-time fault-tolerant applications. Suggestion is to identify all uses of try/catch in the library and make them obey configuration directives.

**Comment by vinniefalco** [comment] 2018-07-03 21:43
This will help
```
namespace detail {
template<class DynamicBuffer>
bool dynamic_prepare(
    boost::optional<typename DynamicBuffer::const_buffers_type>&buffer,
    std::size_t amount);
} // detail
```

**Comment by djarek** [comment] 2018-07-03 22:03
Note that according to https://www.boost.org/doc/libs/develop/libs/beast/doc/html/beast/concepts/DynamicBuffer.html

DynamicBuffers are required to throw `length_error` if `length_error if size() + n` exceeds `max_size()`, so Beast could just check this condition before calling prepare, thus avoiding the need for the try catch block/

**Comment by vinniefalco** [comment] 2018-07-03 22:05
We still need the try/catch block because we want to convert `length_error` into an `error_code`. But this try/catch can be moved into a utility function (e.g. `dynamic_prepare` above) and then conditionally compiled based on `BOOST_NO_EXCEPTIONS` and `BOOST_EXCEPTIONS_DISABLE`. In addition, we can perform the length check you described, and return `false` if the check fails.

**Comment by vinniefalco** [comment] 2018-10-09 21:46
Working on this now

**Comment by vinniefalco** [comment] 2018-10-10 02:48
@djarek how do we handle this:
https://github.com/boostorg/beast/blob/ec1c8ada7a22b274cf6e58c019c2bbe6965f6232/include/boost/beast/http/string_body.hpp#L100

**Comment by djarek** [comment] 2018-10-10 06:42
```
BOOST_TRY
{
  // ...
}
BOOST_CATCH(std::exception const&)
{
  // ...
} BOOST_CATCH_END
```

Catching all exceptions may be a bit too overzealous here, I think the only one that should be handled is `std::bad_alloc`.

**Comment by altf4** [comment] 2021-03-02 15:47
Hi, I wanted to check in on the status of this. Can beast (specifically the websockets) be used with -fno-exceptions today? Sorry if this is in documentation somewhere, I couldn't find it. Thanks!

**Comment by madmongo1** [comment] 2021-03-02 17:55
Not supported at present, but thanks for commenting on this issue. It's from before my time but I'll resurrect it.

**Comment by vinniefalco** [comment] 2021-03-02 18:09
I don't see this ever happening in Beast

**Comment by klemens-morgenstern** [comment] 2022-09-24 06:14
Vinnie, does that mean the issue is rejected?

**Comment by vinniefalco** [comment] 2022-09-25 00:25
Does asio work without exceptions?

**Comment by Kyle-Thompson** [comment] 2023-12-20 05:51
This issue is still marked as open despite #2611 being merged with the description saying it closes this issue. Is this still considered open?

**Comment by ashtum** [comment] 2023-12-20 06:35
> -fno_exceptions

I believe the issue has been resolved, and we can now use Beast with `-fno-exceptions`. Are you experiencing any issues?

**Comment by Kyle-Thompson** [comment] 2023-12-20 17:53
I have not yet used the library, I'm looking at a possible replacement to what I'm currently using and `-fno-exceptions` is a requirement so I wanted to confirm that this issue is resolved despite being still listed as open. Thanks for the quick response.

**Comment by ashtum** [comment] 2023-12-20 17:57
I believe so (and did some tests). Could you confirm, @klemens-morgenstern?

**Comment by klemens-morgenstern** [comment] 2023-12-20 21:30
I think so.

**Closed** 2023-12-21 05:26 UTC
Labels: Feature, Spec
