### ISSUE TITLE
Query builder

### ISSUE THREAD

**Issue by soroshsabz** [boostorg/beast#1585] opened 2019-04-21 20:56 UTC
ITNOA

Hi,

Is there any plan to write some facility like `query builder` ? something like [cpprestsdk uri builder](https://github.com/Microsoft/cpprestsdk/blob/master/Release/include/cpprest/uri_builder.h)

thanks for write great library

**Comment by vinniefalco** [comment] 2019-04-21 20:57
Yes.

**Comment by soroshsabz** [comment] 2019-04-21 21:01
@vinniefalco Thanks a lot, so this issue mark as feature?

**Comment by vinniefalco** [comment] 2019-04-21 21:07
Duplicate of https://github.com/boostorg/beast/issues/787

**Closed by vinniefalco** 2019-04-21 21:07 UTC
