### ISSUE TITLE
[Help] Correctly handle message loop on idle websocket connection

### ISSUE THREAD

**Issue by zptan** [boostorg/beast#2785] opened 2024-01-03 09:27 UTC
We have a few websocket connections that may not be always busy, sometimes they just ping-pong (automatically handled) with server if no request sent, so `io_context.run()` exits and `io_context.stopped()` returns true at that time (_**please correct me if I am wrong**_).

So what is the correct or elegant way to handle message loop?

Always restart `io_context` if it is stopped?

```cc
// Run in a separated thread
while (!shutdown) {
    while (!io_context_.stopped()) {
        io_context_.run();
    }
    io_context_.restart();
}

**Comment by ashtum** [comment] 2024-01-03 09:32
[websocket::stream](https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream.html) handles ping-pong as long as you have an active async_read operation. so you need to always have an async read loop in your design.

**Comment by ashtum** [comment] 2024-01-03 10:01
Based on your use case, you will always have an ongoing `async_write` or `async_read`. Therefore, there is no need to manually handle ping-pong operations; instead, you just need to set the proper timeout options using [websocket::stream::set_option (2 of 3 overloads)](https://www.boost.org/doc/libs/1_84_0/libs/beast/doc/html/beast/ref/boost__beast__websocket__stream/set_option/overload2.html).

As long as you have an unfinished async operation, `io_context.run()` should not return. [io_context::run (1 of 2 overloads)](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/io_context/run/overload1.html).

**Comment by ashtum** [comment] 2024-01-03 12:59
Is this part of a library interface and you hide the `io_context` from the user?
You can create an [executor_work_guard](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/executor_work_guard.html) to prevent `io_context` from stop but in a well designed async application you rarely need to use this (because there is always something to wait for).

**Comment by ashtum** [comment] 2024-01-04 11:28
You cannot have more than one ongoing `async_read` operation; you have to wait until it completes to initiate another one. This is true for `async_write` as well.

> I tried [executor_work_guard](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/executor_work_guard.html) but it does not work.

Here is a simple usage example: https://godbolt.org/z/W58hjjvza

```C++
#include <boost/asio.hpp>

using namespace boost;

int main()
{
  asio::io_context ioc;

  auto wg = asio::make_work_guard(ioc);

  ioc.run();
}
```

An alternative for you might be to run `async_read` in a loop and send the received messages to an [experimental::basic_channel](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/experimental__basic_channel.html). This way, `async_read` takes care of ping-pong operations. After your write operation, you can wait on the channel to read the response.

If this doesn't work for you, please explain your problem more thoroughly and provide example code of your interfaces so that I can better understand what you want to achieve.

**Comment by ashtum** [comment] 2024-01-04 14:28
> Oh sorry, the code I pasted in my last reply is a little confusing, actually like this (using dispatch())

The problem is not just about data race. You can't have more than one `async_read` even from a single thread because each one might need multiple calls to `async_read_some` to gather all the required data from the socket. When you have more than one `async_read`, each part of the data can interleave with each other. [async_read (1 of 8 overloads)](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/async_read/overload1.html).

> So it is not a typical websocket scenario.

Could you please explain would be the interface of the library?

To my understanding, your concern about ping-pong operations would be addressed by always having an async_read operation waiting. It takes care of the ping-pong, and there is no need to handle it manually.

If there is a guarantee of having a single response for each request, you can send responses in your async_read loop to an [experimental::basic_channel](https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/experimental__basic_channel.html) and read from it after the async_write completes.

**Comment by vinniefalco** [comment] 2024-01-12 17:48
`executor_work_guard` is the correct solution. Please show the code using the guard.

**Closed as completed** 2024-01-13 02:03 UTC
